export interface ModelField {
  name: string;
  display: string;
  type: "string" | "number" | "boolean" | "date" | "json" | "enum" | "relation";
  required?: boolean;
  editable?: boolean;
  enumValues?: string[];
  relationModel?: string;
  isArray?: boolean;
  hidden?: boolean;
}

export interface ModelConfig {
  name: string;
  plural: string;
  apiPath: string;
  icon: string;
  fields: ModelField[];
  displayField: string;
  category: string;
}

export const modelConfigs: ModelConfig[] = [
  {
    name: "User",
    plural: "Users",
    apiPath: "user",
    icon: "users",
    category: "Users & Teams",
    displayField: "email",
    fields: [
      { name: "id", display: "ID", type: "string", editable: false },
      { name: "email", display: "Email", type: "string", required: true },
      { name: "name", display: "Name", type: "string" },
      { name: "role", display: "Role", type: "enum", enumValues: ["ADMIN", "USER"], required: true },
      { name: "createdAt", display: "Created At", type: "date", editable: false },
      { name: "updatedAt", display: "Updated At", type: "date", editable: false },
    ],
  },
  {
    name: "Team",
    plural: "Teams",
    apiPath: "team",
    icon: "building",
    category: "Users & Teams",
    displayField: "name",
    fields: [
      { name: "id", display: "ID", type: "string", editable: false },
      { name: "name", display: "Name", type: "string", required: true },
      { name: "createdAt", display: "Created At", type: "date", editable: false },
      { name: "updatedAt", display: "Updated At", type: "date", editable: false },
    ],
  },
  {
    name: "TeamMember",
    plural: "Team Members",
    apiPath: "teamMember",
    icon: "user-check",
    category: "Users & Teams",
    displayField: "id",
    fields: [
      { name: "id", display: "ID", type: "string", editable: false },
      { name: "teamId", display: "Team ID", type: "string", required: true },
      { name: "userId", display: "User ID", type: "string", required: true },
      { name: "role", display: "Role", type: "enum", enumValues: ["OWNER", "ADMIN", "MEMBER", "VIEWER"], required: true },
      { name: "createdAt", display: "Created At", type: "date", editable: false },
    ],
  },
  {
    name: "TeamInvite",
    plural: "Team Invites",
    apiPath: "teamInvite",
    icon: "mail",
    category: "Users & Teams",
    displayField: "email",
    fields: [
      { name: "id", display: "ID", type: "string", editable: false },
      { name: "teamId", display: "Team ID", type: "string", required: true },
      { name: "email", display: "Email", type: "string", required: true },
      { name: "role", display: "Role", type: "enum", enumValues: ["OWNER", "ADMIN", "MEMBER", "VIEWER"] },
      { name: "token", display: "Token", type: "string", editable: false },
      { name: "invitedBy", display: "Invited By", type: "string", required: true },
      { name: "expiresAt", display: "Expires At", type: "date" },
      { name: "acceptedAt", display: "Accepted At", type: "date" },
      { name: "createdAt", display: "Created At", type: "date", editable: false },
    ],
  },
  {
    name: "TeamSettings",
    plural: "Team Settings",
    apiPath: "teamSettings",
    icon: "settings",
    category: "Users & Teams",
    displayField: "teamId",
    fields: [
      { name: "id", display: "ID", type: "string", editable: false },
      { name: "teamId", display: "Team ID", type: "string", required: true },
      { name: "ascIssuerId", display: "ASC Issuer ID", type: "string" },
      { name: "ascKeyId", display: "ASC Key ID", type: "string" },
      { name: "ascAccountConnectRequestedAt", display: "ASC Connect Requested At", type: "date" },
      { name: "ascAutoConnectedAt", display: "ASC Connect Connected At", type: "date" },
      { name: "ascAutoKeyId", display: "ASC Connect Key ID", type: "string" },
      { name: "mcpEnabled", display: "MCP Enabled", type: "boolean" },
      { name: "githubUsername", display: "GitHub Username", type: "string" },
      { name: "updatedAt", display: "Updated At", type: "date", editable: false },
    ],
  },
  {
    name: "App",
    plural: "Apps",
    apiPath: "app",
    icon: "smartphone",
    category: "Apps",
    displayField: "name",
    fields: [
      { name: "id", display: "ID", type: "string", editable: false },
      { name: "bundleId", display: "Bundle ID", type: "string", required: true },
      { name: "name", display: "Name", type: "string", required: true },
      { name: "teamId", display: "Team ID", type: "string" },
      { name: "country", display: "Country", type: "string" },
      { name: "isOwnApp", display: "Own App", type: "boolean" },
      { name: "currentTitle", display: "Current Title", type: "string" },
      { name: "currentSubtitle", display: "Current Subtitle", type: "string" },
      { name: "currentKeywords", display: "Current Keywords", type: "string", hidden: true },
      { name: "githubRepoFullName", display: "GitHub Repo Full Name", type: "string" },
      { name: "createdAt", display: "Created At", type: "date", editable: false },
      { name: "updatedAt", display: "Updated At", type: "date", editable: false },
    ],
  },
  {
    name: "AppSnapshot",
    plural: "App Snapshots",
    apiPath: "appSnapshot",
    icon: "camera",
    category: "Apps",
    displayField: "title",
    fields: [
      { name: "id", display: "ID", type: "string", editable: false },
      { name: "appId", display: "App ID", type: "string", required: true },
      { name: "title", display: "Title", type: "string", required: true },
      { name: "subtitle", display: "Subtitle", type: "string" },
      { name: "description", display: "Description", type: "string", hidden: true },
      { name: "rating", display: "Rating", type: "number" },
      { name: "ratingsCount", display: "Ratings Count", type: "number" },
      { name: "version", display: "Version", type: "string" },
      { name: "developerName", display: "Developer Name", type: "string" },
      { name: "category", display: "Category", type: "string" },
      { name: "scrapedAt", display: "Scraped At", type: "date", editable: false },
    ],
  },
  {
    name: "Keyword",
    plural: "Keywords",
    apiPath: "keyword",
    icon: "search",
    category: "ASO",
    displayField: "term",
    fields: [
      { name: "id", display: "ID", type: "string", editable: false },
      { name: "term", display: "Term", type: "string", required: true },
      { name: "country", display: "Country", type: "string" },
      { name: "language", display: "Language", type: "string" },
      { name: "popularity", display: "Popularity", type: "number" },
      { name: "difficulty", display: "Difficulty", type: "number" },
      { name: "searchVolume", display: "Search Volume", type: "number" },
      { name: "createdAt", display: "Created At", type: "date", editable: false },
      { name: "updatedAt", display: "Updated At", type: "date", editable: false },
    ],
  },
  {
    name: "KeywordRanking",
    plural: "Keyword Rankings",
    apiPath: "keywordRanking",
    icon: "trending-up",
    category: "ASO",
    displayField: "id",
    fields: [
      { name: "id", display: "ID", type: "string", editable: false },
      { name: "keywordId", display: "Keyword ID", type: "string", required: true },
      { name: "appId", display: "App ID", type: "string", required: true },
      { name: "rank", display: "Rank", type: "number" },
      { name: "country", display: "Country", type: "string" },
      { name: "trackedAt", display: "Tracked At", type: "date", editable: false },
    ],
  },
  {
    name: "ASOSuggestion",
    plural: "ASO Suggestions",
    apiPath: "asoSuggestion",
    icon: "lightbulb",
    category: "ASO",
    displayField: "type",
    fields: [
      { name: "id", display: "ID", type: "string", editable: false },
      { name: "type", display: "Type", type: "enum", enumValues: ["TITLE", "SUBTITLE", "KEYWORDS", "DESCRIPTION", "SCREENSHOT_ORDER"], required: true },
      { name: "locale", display: "Locale", type: "string" },
      { name: "suggestedValue", display: "Suggested Value", type: "string", hidden: true },
      { name: "reasoning", display: "Reasoning", type: "string", hidden: true },
      { name: "appBundleId", display: "App Bundle ID", type: "string" },
      { name: "confidenceScore", display: "Confidence Score", type: "number" },
      { name: "status", display: "Status", type: "enum", enumValues: ["PENDING", "APPROVED", "APPLIED", "REJECTED", "EXPIRED"] },
      { name: "aiProvider", display: "AI Provider", type: "string" },
      { name: "aiModel", display: "AI Model", type: "string" },
      { name: "createdAt", display: "Created At", type: "date", editable: false },
    ],
  },
  {
    name: "AsoExperiment",
    plural: "ASO Experiments",
    apiPath: "asoExperiment",
    icon: "flask-conical",
    category: "ASO",
    displayField: "type",
    fields: [
      { name: "id", display: "ID", type: "string", editable: false },
      { name: "appId", display: "App ID", type: "string", required: true },
      { name: "type", display: "Type", type: "enum", enumValues: ["KEYWORD_ADD", "KEYWORD_REMOVE", "KEYWORD_REPLACE", "TITLE_CHANGE", "SUBTITLE_CHANGE"] },
      { name: "fromValue", display: "From Value", type: "string" },
      { name: "toValue", display: "To Value", type: "string" },
      { name: "reason", display: "Reason", type: "string", hidden: true },
      { name: "confidence", display: "Confidence", type: "number" },
      { name: "status", display: "Status", type: "enum", enumValues: ["PENDING", "APPROVED", "DEPLOYED", "EVALUATED", "REJECTED"] },
      { name: "createdAt", display: "Created At", type: "date", editable: false },
    ],
  },
  {
    name: "CompetitorRelation",
    plural: "Competitor Relations",
    apiPath: "competitorRelation",
    icon: "swords",
    category: "Apps",
    displayField: "id",
    fields: [
      { name: "id", display: "ID", type: "string", editable: false },
      { name: "appId", display: "App ID", type: "string", required: true },
      { name: "competitorId", display: "Competitor ID", type: "string", required: true },
      { name: "relevanceScore", display: "Relevance Score", type: "number" },
      { name: "addedAt", display: "Added At", type: "date", editable: false },
    ],
  },
  {
    name: "AppStoreAnalytics",
    plural: "App Store Analytics",
    apiPath: "appStoreAnalytics",
    icon: "bar-chart-3",
    category: "Analytics",
    displayField: "bundleId",
    fields: [
      { name: "id", display: "ID", type: "string", editable: false },
      { name: "bundleId", display: "Bundle ID", type: "string", required: true },
      { name: "reportDate", display: "Report Date", type: "date" },
      { name: "country", display: "Country", type: "string" },
      { name: "downloads", display: "Downloads", type: "number" },
      { name: "impressions", display: "Impressions", type: "number" },
      { name: "pageViews", display: "Page Views", type: "number" },
      { name: "proceeds", display: "Proceeds", type: "number" },
      { name: "createdAt", display: "Created At", type: "date", editable: false },
    ],
  },
  {
    name: "AppReview",
    plural: "App Reviews",
    apiPath: "appReview",
    icon: "star",
    category: "Analytics",
    displayField: "title",
    fields: [
      { name: "id", display: "ID", type: "string", editable: false },
      { name: "ascReviewId", display: "ASC Review ID", type: "string" },
      { name: "bundleId", display: "Bundle ID", type: "string", required: true },
      { name: "rating", display: "Rating", type: "number", required: true },
      { name: "title", display: "Title", type: "string" },
      { name: "body", display: "Body", type: "string", hidden: true },
      { name: "reviewerNickname", display: "Reviewer Nickname", type: "string" },
      { name: "territory", display: "Territory", type: "string" },
      { name: "reviewedAt", display: "Reviewed At", type: "date" },
      { name: "createdAt", display: "Created At", type: "date", editable: false },
    ],
  },
  {
    name: "CompetitorReview",
    plural: "Competitor Reviews",
    apiPath: "competitorReview",
    icon: "message-square",
    category: "Analytics",
    displayField: "id",
    fields: [
      { name: "id", display: "ID", type: "string", editable: false },
      { name: "appId", display: "App ID", type: "string", required: true },
      { name: "rating", display: "Rating", type: "number", required: true },
      { name: "title", display: "Title", type: "string" },
      { name: "body", display: "Body", type: "string", hidden: true },
      { name: "author", display: "Author", type: "string" },
      { name: "territory", display: "Territory", type: "string" },
      { name: "reviewedAt", display: "Reviewed At", type: "date" },
      { name: "createdAt", display: "Created At", type: "date", editable: false },
    ],
  },
  {
    name: "CompetitorReviewSummary",
    plural: "Review Summaries",
    apiPath: "competitorReviewSummary",
    icon: "message-square",
    category: "Analytics",
    displayField: "appId",
    fields: [
      { name: "id", display: "ID", type: "string", editable: false },
      { name: "appId", display: "App ID", type: "string", required: true },
      { name: "reviewCount", display: "Review Count", type: "number" },
      { name: "averageRating", display: "Average Rating", type: "number" },
      { name: "summary", display: "Summary", type: "string", hidden: true },
      { name: "sentiment", display: "Sentiment", type: "string" },
      { name: "aiProvider", display: "AI Provider", type: "string" },
      { name: "aiModel", display: "AI Model", type: "string" },
      { name: "createdAt", display: "Created At", type: "date", editable: false },
    ],
  },
  {
    name: "AppMetadataChange",
    plural: "Metadata Changes",
    apiPath: "appMetadataChange",
    icon: "file-diff",
    category: "Analytics",
    displayField: "field",
    fields: [
      { name: "id", display: "ID", type: "string", editable: false },
      { name: "appId", display: "App ID", type: "string", required: true },
      { name: "field", display: "Field", type: "string", required: true },
      { name: "oldValue", display: "Old Value", type: "string", hidden: true },
      { name: "newValue", display: "New Value", type: "string", hidden: true },
      { name: "detectedAt", display: "Detected At", type: "date", editable: false },
    ],
  },
  {
    name: "ScreenshotJob",
    plural: "Screenshot Jobs",
    apiPath: "screenshotJob",
    icon: "image",
    category: "Jobs (2)",
    displayField: "commitSha",
    fields: [
      { name: "id", display: "ID", type: "string", editable: false },
      { name: "appId", display: "App ID", type: "string", required: true },
      { name: "commitSha", display: "Commit SHA", type: "string" },
      { name: "commitMessage", display: "Commit Message", type: "string" },
      { name: "branch", display: "Branch", type: "string" },
      { name: "status", display: "Status", type: "enum", enumValues: ["PENDING", "RUNNING", "COMPLETED", "FAILED"] },
      { name: "error", display: "Error", type: "string", hidden: true },
      { name: "startedAt", display: "Started At", type: "date" },
      { name: "completedAt", display: "Completed At", type: "date" },
      { name: "createdAt", display: "Created At", type: "date", editable: false },
    ],
  },
  {
    name: "BuildJob",
    plural: "Build Jobs",
    apiPath: "buildJob",
    icon: "hammer",
    category: "Jobs (2)",
    displayField: "id",
    fields: [
      { name: "id", display: "ID", type: "string", editable: false },
      { name: "appId", display: "App ID", type: "string", required: true },
      { name: "branch", display: "Branch", type: "string" },
      { name: "commitSha", display: "Commit SHA", type: "string" },
      { name: "status", display: "Status", type: "enum", enumValues: ["PENDING", "RUNNING", "COMPLETED", "FAILED"] },
      { name: "error", display: "Error", type: "string", hidden: true },
      { name: "startedAt", display: "Started At", type: "date" },
      { name: "completedAt", display: "Completed At", type: "date" },
      { name: "createdAt", display: "Created At", type: "date", editable: false },
    ],
  },
  {
    name: "OAuthClient",
    plural: "OAuth Clients",
    apiPath: "oauthClient",
    icon: "key",
    category: "System",
    displayField: "name",
    fields: [
      { name: "id", display: "ID", type: "string", editable: false },
      { name: "clientId", display: "Client ID", type: "string", required: true },
      { name: "clientSecret", display: "Client Secret", type: "string", required: true },
      { name: "name", display: "Name", type: "string", required: true },
      { name: "userId", display: "User ID", type: "string" },
      { name: "redirectUris", display: "Redirect URIs", type: "json" },
      { name: "createdAt", display: "Created At", type: "date", editable: false },
    ],
  },
  {
    name: "DeviceToken",
    plural: "Device Tokens",
    apiPath: "deviceToken",
    icon: "bell",
    category: "System",
    displayField: "token",
    fields: [
      { name: "id", display: "ID", type: "string", editable: false },
      { name: "token", display: "Token", type: "string", required: true },
      { name: "userId", display: "User ID", type: "string" },
      { name: "bundleId", display: "Bundle ID", type: "string" },
      { name: "platform", display: "Platform", type: "string" },
      { name: "isActive", display: "Is Active", type: "boolean" },
      { name: "createdAt", display: "Created At", type: "date", editable: false },
    ],
  },
  {
    name: "PushNotificationLog",
    plural: "Push Notification Logs",
    apiPath: "pushNotificationLog",
    icon: "send",
    category: "System",
    displayField: "title",
    fields: [
      { name: "id", display: "ID", type: "string", editable: false },
      { name: "deviceToken", display: "Device Token", type: "string" },
      { name: "title", display: "Title", type: "string" },
      { name: "body", display: "Body", type: "string" },
      { name: "category", display: "Category", type: "string" },
      { name: "status", display: "Status", type: "string" },
      { name: "error", display: "Error", type: "string" },
      { name: "sentAt", display: "Sent At", type: "date", editable: false },
    ],
  },
  {
    name: "PasskeyCredential",
    plural: "Passkey Credentials",
    apiPath: "passkeyCredential",
    icon: "fingerprint",
    category: "Users & Teams",
    displayField: "id",
    fields: [
      { name: "id", display: "ID", type: "string", editable: false },
      { name: "userId", display: "User ID", type: "string", required: true },
      { name: "credentialId", display: "Credential ID", type: "string", editable: false },
      { name: "deviceType", display: "Device Type", type: "string" },
      { name: "backedUp", display: "Backed Up", type: "boolean" },
      { name: "name", display: "Name", type: "string" },
      { name: "createdAt", display: "Created At", type: "date", editable: false },
      { name: "lastUsedAt", display: "Last Used At", type: "date" },
    ],
  },
  {
    name: "Subscription",
    plural: "Subscriptions (raw)",
    apiPath: "subscription",
    icon: "credit-card",
    category: "Users & Teams",
    displayField: "lemonSubscriptionId",
    fields: [
      { name: "id", display: "ID", type: "string", editable: false },
      { name: "teamId", display: "Team ID", type: "string", editable: false },
      { name: "lemonSubscriptionId", display: "LS Subscription ID", type: "string", editable: false },
      { name: "lemonCustomerId", display: "LS Customer ID", type: "string", editable: false },
      { name: "lemonOrderId", display: "LS Order ID", type: "string", editable: false },
      { name: "lemonProductId", display: "LS Product ID", type: "string", editable: false },
      { name: "lemonVariantId", display: "LS Variant ID", type: "string", editable: false },
      { name: "status", display: "Status", type: "string", editable: false },
      { name: "interval", display: "Interval", type: "enum", enumValues: ["monthly", "yearly"], editable: false },
      { name: "cardBrand", display: "Card Brand", type: "string", editable: false },
      { name: "cardLastFour", display: "Card Last 4", type: "string", editable: false },
      { name: "renewsAt", display: "Renews At", type: "date", editable: false },
      { name: "endsAt", display: "Ends At", type: "date", editable: false },
      { name: "trialEndsAt", display: "Trial Ends At", type: "date", editable: false },
      { name: "customerPortalUrl", display: "Customer Portal URL", type: "string", editable: false },
      { name: "updatePaymentMethodUrl", display: "Update Payment URL", type: "string", editable: false, hidden: true },
      { name: "createdAt", display: "Created At", type: "date", editable: false },
      { name: "updatedAt", display: "Updated At", type: "date", editable: false },
    ],
  },
  {
    name: "AscRateLimit",
    plural: "ASC Rate Limits",
    apiPath: "ascRateLimit",
    icon: "gauge",
    category: "System",
    displayField: "teamId",
    fields: [
      { name: "id", display: "ID", type: "string", editable: false },
      { name: "teamId", display: "Team ID", type: "string", editable: false },
      { name: "hourLimit", display: "Hour Limit", type: "number", editable: false },
      { name: "hourRemaining", display: "Hour Remaining", type: "number", editable: false },
      { name: "updatedAt", display: "Updated At", type: "date", editable: false },
    ],
  },
];

export const modelCategories = [...new Set(modelConfigs.map((m) => m.category))];

export function getModelConfig(apiPath: string): ModelConfig | undefined {
  return modelConfigs.find((m) => m.apiPath === apiPath);
}
