import { Router } from "express";
import { prisma, logger } from "../../config";
import { requireAuth, requireTeamAdmin, loadTeamSettings } from "../auth";
import { encrypt, decryptNullable } from "../../config/encryption";
import { listAppleAdsOrgs, listAppleAdsCampaigns } from "../../services/apple-ads";

export const appleAdsRouter = Router();
appleAdsRouter.use(requireAuth);

appleAdsRouter.get("/status", loadTeamSettings, async (req, res) => {
  const s = req.teamSettings;
  res.json({
    connected: !!s?.appleAdsConnectedAt,
    orgId: s?.appleAdsOrgId ?? null,
    orgName: s?.appleAdsOrgName ?? null,
    connectedAt: s?.appleAdsConnectedAt?.toISOString() ?? null,
  });
});

appleAdsRouter.get("/campaigns", loadTeamSettings, async (req, res) => {
  const s = req.teamSettings;
  if (!s?.appleAdsConnectedAt || !s.appleAdsOrgId || !s.appleAdsClientId || !s.appleAdsTeamId || !s.appleAdsKeyId || !s.appleAdsPrivateKey) {
    res.status(400).json({ error: "Apple Search Ads is not connected" });
    return;
  }

  try {
    const campaigns = await listAppleAdsCampaigns({
      orgId: s.appleAdsOrgId,
      clientId: s.appleAdsClientId,
      teamId: s.appleAdsTeamId,
      keyId: s.appleAdsKeyId,
      privateKey: decryptNullable(s.appleAdsPrivateKey)!,
    });
    res.json({ campaigns });
  } catch (err: any) {
    logger.error("[apple-ads] campaigns fetch error", {
      err: String(err?.message ?? err),
      status: err?.response?.status,
      body: err?.response?.data,
    });
    res.status(500).json({ error: "Failed to load campaigns from Apple Search Ads" });
  }
});

appleAdsRouter.post("/connect", async (req, res) => {
  try {
    if (!(await requireTeamAdmin(req, res))) return;
    const teamId = req.user!.teamId!;

    const { orgId, clientId, teamId: appleTeamId, keyId, privateKey } = req.body as Record<string, string>;

    if (!clientId || !appleTeamId || !keyId || !privateKey) {
      res.status(400).json({ error: "clientId, teamId, keyId and privateKey are all required" });
      return;
    }

    if (privateKey.includes("BEGIN PUBLIC KEY")) {
      res.status(400).json({
        error:
          "That's a public key. Apple Search Ads keys are generated by you: paste the private half you generated, not the one you uploaded to Apple.",
      });
      return;
    }

    const orgCreds = { clientId, teamId: appleTeamId, keyId, privateKey };

    let orgs: { orgId: string; orgName: string }[];
    try {
      orgs = await listAppleAdsOrgs(orgCreds);
    } catch (err: any) {
      logger.warn("[apple-ads] credential verification failed", {
        err: String(err?.message ?? err),
        status: err?.response?.status,
        body: err?.response?.data,
      });
      res.status(400).json({ error: "Could not verify these credentials with Apple Search Ads. Double-check them and try again." });
      return;
    }

    // A key can see more than one org when it belongs to an agency/parent account.
    // Without an explicit pick we can't tell which one actually has the campaigns,
    // so hand the list back to the client instead of guessing.
    let selected = orgs.find((o) => o.orgId === orgId);
    if (!selected) {
      if (orgId) {
        res.status(400).json({ error: "That organization isn't accessible with this API key." });
        return;
      }
      if (orgs.length > 1) {
        res.json({ needsOrgSelection: true, orgs });
        return;
      }
      selected = orgs[0];
    }

    const connectedAt = new Date();
    await prisma.teamSettings.upsert({
      where: { teamId },
      create: {
        teamId,
        appleAdsOrgId: selected.orgId,
        appleAdsOrgName: selected.orgName,
        appleAdsClientId: clientId,
        appleAdsTeamId: appleTeamId,
        appleAdsKeyId: keyId,
        appleAdsPrivateKey: encrypt(privateKey),
        appleAdsConnectedAt: connectedAt,
      },
      update: {
        appleAdsOrgId: selected.orgId,
        appleAdsOrgName: selected.orgName,
        appleAdsClientId: clientId,
        appleAdsTeamId: appleTeamId,
        appleAdsKeyId: keyId,
        appleAdsPrivateKey: encrypt(privateKey),
        appleAdsConnectedAt: connectedAt,
      },
    });

    res.json({ ok: true, orgId: selected.orgId, orgName: selected.orgName, connectedAt: connectedAt.toISOString() });
  } catch (err: any) {
    logger.error("[apple-ads] connect error", { err: String(err?.message ?? err) });
    res.status(500).json({ error: err.message });
  }
});

appleAdsRouter.get("/orgs", loadTeamSettings, async (req, res) => {
  const s = req.teamSettings;
  if (!s?.appleAdsConnectedAt || !s.appleAdsClientId || !s.appleAdsTeamId || !s.appleAdsKeyId || !s.appleAdsPrivateKey) {
    res.status(400).json({ error: "Apple Search Ads is not connected" });
    return;
  }

  try {
    const orgs = await listAppleAdsOrgs({
      clientId: s.appleAdsClientId,
      teamId: s.appleAdsTeamId,
      keyId: s.appleAdsKeyId,
      privateKey: decryptNullable(s.appleAdsPrivateKey)!,
    });
    res.json({ orgs, selectedOrgId: s.appleAdsOrgId });
  } catch (err: any) {
    logger.error("[apple-ads] orgs fetch error", { err: String(err?.message ?? err) });
    res.status(500).json({ error: "Failed to load organizations from Apple Search Ads" });
  }
});

appleAdsRouter.post("/org", async (req, res) => {
  try {
    if (!(await requireTeamAdmin(req, res))) return;
    const teamId = req.user!.teamId!;

    const s = await prisma.teamSettings.findUnique({ where: { teamId } });
    if (!s?.appleAdsConnectedAt || !s.appleAdsClientId || !s.appleAdsTeamId || !s.appleAdsKeyId || !s.appleAdsPrivateKey) {
      res.status(400).json({ error: "Apple Search Ads is not connected" });
      return;
    }

    const { orgId } = req.body as { orgId?: string };
    if (!orgId) {
      res.status(400).json({ error: "orgId is required" });
      return;
    }

    const orgs = await listAppleAdsOrgs({
      clientId: s.appleAdsClientId,
      teamId: s.appleAdsTeamId,
      keyId: s.appleAdsKeyId,
      privateKey: decryptNullable(s.appleAdsPrivateKey)!,
    });
    const match = orgs.find((o) => o.orgId === orgId);
    if (!match) {
      res.status(400).json({ error: "That organization isn't accessible with this API key." });
      return;
    }

    await prisma.teamSettings.update({
      where: { teamId },
      data: { appleAdsOrgId: match.orgId, appleAdsOrgName: match.orgName },
    });

    res.json({ ok: true, orgId: match.orgId, orgName: match.orgName });
  } catch (err: any) {
    logger.error("[apple-ads] org switch error", { err: String(err?.message ?? err) });
    res.status(500).json({ error: err.message });
  }
});

appleAdsRouter.post("/disconnect", async (req, res) => {
  try {
    if (!(await requireTeamAdmin(req, res))) return;
    const teamId = req.user!.teamId!;

    await prisma.teamSettings.updateMany({
      where: { teamId },
      data: {
        appleAdsOrgId: null,
        appleAdsOrgName: null,
        appleAdsClientId: null,
        appleAdsTeamId: null,
        appleAdsKeyId: null,
        appleAdsPrivateKey: null,
        appleAdsConnectedAt: null,
      },
    });

    res.json({ ok: true });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});
